version: '3'

# This file is only there for developer convenience,
# it is not used in testing or deployments

x-python: &python
  build:
    context: ./
    dockerfile: ./Dockerfile
    args:
      TARGET: ${TARGET}
  command: start:${TARGET}

services:
  api:
    <<: *python

  database:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=textflowrhyme
    ports:
      - 5432:5432
