version: '3'

# This file is only there for developer convenience 
# and should not be used for deployments.

x-python: &python
  build:
    context: ./
    dockerfile: ./Dockerfile
    args:
      TARGET: ${TARGET}
  links:
    - postgres
  environment:
    - DATABASE_NAME=textflowrhyme
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=password1234
    - DATABASE_HOST=postgres
    - DATABASE_PORT=5432
  command: start:${TARGET}

services:
  uvicorn:
    <<: *python

  postgres:
    image: postgres:alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=textflowrhyme
    ports:
      - 5432:5432  # For local development only
