name: Testing

on:
  push:
    branches-ignore:
      - master
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start backend dependencies
        run: |
          TARGET=testing docker compose up postgres -d

      - name: Build container
        run: |
          TARGET=testing docker compose build uvicorn

      - name: Lint & Test
        run: |
          TARGET=testing docker compose run --rm uvicorn start:testing
